version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis/redis-stack
    container_name: redis
    ports:
      - "6379:6379"
      - "8001:8001"

  server:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: server
    ports:
      - 4000:4000
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://admin:password@mongodb:27017/ecommerce?authSource=admin
      - REDIS_URI=redis://redis
    depends_on:
      - mongodb
      - redis
    develop:
      watch:
        - path: ./backend/package*.json
          action: rebuild
        - path: ./backend
          target: /app
          action: sync

  client:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: client
    ports:
      - 5173:5173
    env_file:
      - ./frontend/.env
    depends_on:
      - server
    develop:
      watch:
        - path: ./frontend/package*.json
          action: rebuild
        - path: ./frontend
          target: /app
          action: sync

volumes:
  mongodb_data:
    driver: local
